from typing import TypedDict, List, Dict, Any, Optional

class AgentState(TypedDict):
    # Inputs
    start_location: str
    destination: str
    budget: float
    start_date: str
    end_date: str
    travelers: int
    interests: List[str]
    style: str  # Balanced, Cheapest, Comfortable, Luxury
    transport_pref: str
    hotel_pref: str
    
    # Processed constraints
    num_days: int
    extracted_interests: List[str]
    
    # Outputs collected by agents
    transport_options: List[Dict[str, Any]]
    selected_transport: Optional[Dict[str, Any]]
    
    hotel_options: List[Dict[str, Any]]
    selected_hotel: Optional[Dict[str, Any]]
    
    attractions: List[Dict[str, Any]]
    weather_forecast: List[Dict[str, Any]]
    
    itinerary: List[Dict[str, Any]]  # Day-by-day timetable
    budget_breakdown: Dict[str, Any]
    svg_map: Optional[str]  # Asynchronous visual route map generated by svgAgent
    
    # State tracking
    logs: List[str]  # Execution timeline (user-facing messages)
    validation_logs: List[str]  # Issues found during validation
    is_valid: bool
    retry_count: int
    error_message: Optional[str]
    suggested_adjustments: Optional[str]  # Feedback for replanning

